BackendBundle\Entity\PrivateMessage:
    type: entity
    table: private_messages
    indexes:
        fk_emiter_privates:
            columns:
                - emiter
        fk_receiver_privates:
            columns:
                - receiver
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        message:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        file:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: FILE
        readed:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
    manyToOne:
        emiter:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                emiter:
                    referencedColumnName: id
            orphanRemoval: false
        receiver:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                receiver:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
